language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpunit